# Mapa de calor

```{r eval=TRUE,  echo=FALSE,cache=FALSE,  comment=FALSE, warning=FALSE,message=FALSE}

# Carregar os pacotes -----------------------

library(tidyverse)
library(highcharter)
library(shiny)
library(knitr)
library(kableExtra)

# Dados --------------------------------

dados_plot <- data.frame(
  ano = c(rep(2017, 5), rep(2018, 5), rep(2019, 5)),
  tipo = c("A", "B", "C", "D", "E", "A", "B", "C", "D", "E", "A", "B", "C", "D", "E"),
  pct = c(83.46, 9.06, 0.058, 1.59, 5.91, 80.05, 6.85, 1.59, 0.03, 11.48, 63.6, 28, .14, .05, 8.01)
)


fluidPage(
  fluidRow(
    column(
      width = 12,
      
      h4(style="font-weight: bold;", "Gráfico exemplo - Mapa de calor "),
      
      dados_plot %>% 
        hchart(
          type = 'heatmap', 
          hcaes(
            x = ano, 
            y = tipo, 
            value = pct
          ),
          name = "Teste"
        ) %>% 
        hc_plotOptions(
          series = list(
            dataLabels = list(
              enabled = TRUE, 
              format = '{point.value:.2f}%'
            )
          )
        ) %>% 
        hc_colorAxis(
          maxColor = '#222c6a',
          minColor = '#009761'
        ) %>% 
        hc_tooltip(
          pointFormat = paste('{point.tipo}: <b>{point.pct:.,2f}%</b><br>')
        ) %>% 
        hc_yAxis(title = list(text = 'Tipo')) %>%
        hc_xAxis(title = list(text = 'Ano'))  %>%
        hc_legend(enabled = FALSE) 
    )
  )
  
)

```

```R
library(tidyverse)
library(highcharter)


 dados_plot %>% 
      hchart(
        type = 'heatmap', 
        hcaes(
          x = ano, 
          y = tipo, 
          value = pct
        ),
        name = "Teste"
      ) %>% 
      hc_plotOptions(
        series = list(
          dataLabels = list(
            enabled = TRUE, 
            format = '{point.value:.2f}%'
          )
        )
      ) %>% 
      hc_colorAxis(
        maxColor = '#222c6a',
        minColor = '#009761'
      ) %>% 
      hc_tooltip(
        pointFormat = paste('{point.tipo}: <b>{point.pct:.,2f}%</b><br>')
      ) %>% 
      hc_yAxis(title = list(text = 'Tipo')) %>%
      hc_xAxis(title = list(text = 'Ano'))  %>%
      hc_legend(enabled = FALSE) 

```

```{r eval=TRUE,  echo=FALSE,cache=FALSE,  comment=FALSE, warning=FALSE,message=FALSE}
kable(dados_plot, align = "c", row.names = FALSE, digits = 2) %>%
      kable_styling(bootstrap_options = c("hover", "condensed", "responsive"), font_size = 11) %>% 
      row_spec(0, background = "#023047", color = "#FFF")
```
